version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ProductoMC
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ProductoMC
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data